from . import EndpointDef, Param, REALM

PROVIDER_ID = Param("provider_id", "ID of the authenticator provider")
CONFIG_ID = Param("id", "ID of the authenticator configuration")
EXECUTION_ID = Param("execution_id", "ID of the authentication execution")
FLOW_ALIAS = Param("flow_alias", "Alias of the authentication flow")
FLOW_ID = Param("id", "ID of the authentication flow")
ALIAS = Param("alias", "Alias of the required action")

ENDPOINTS: list[EndpointDef] = [
    # ── Authenticator Providers ──────────────────────────────────────────
    EndpointDef(
        name="list_authenticator_providers",
        description="List all authenticator providers available in the realm.",
        method="GET",
        path="/admin/realms/{realm}/authentication/authenticator-providers",
        path_params=[REALM],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="list_client_authenticator_providers",
        description="List all client authenticator providers available in the realm.",
        method="GET",
        path="/admin/realms/{realm}/authentication/client-authenticator-providers",
        path_params=[REALM],
        query_params=[],
        body_param=None,
    ),
    # ── Authenticator Config Description ─────────────────────────────────
    EndpointDef(
        name="get_authenticator_config_description",
        description="Get the configuration description for a specific authenticator provider.",
        method="GET",
        path="/admin/realms/{realm}/authentication/config-description/{provider_id}",
        path_params=[REALM, PROVIDER_ID],
        query_params=[],
        body_param=None,
    ),
    # ── Authenticator Config ─────────────────────────────────────────────
    EndpointDef(
        name="delete_authenticator_config",
        description="Delete an authenticator configuration by ID.",
        method="DELETE",
        path="/admin/realms/{realm}/authentication/config/{id}",
        path_params=[REALM, CONFIG_ID],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="get_authenticator_config",
        description="Get an authenticator configuration by ID.",
        method="GET",
        path="/admin/realms/{realm}/authentication/config/{id}",
        path_params=[REALM, CONFIG_ID],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="update_authenticator_config",
        description="Update an authenticator configuration by ID.",
        method="PUT",
        path="/admin/realms/{realm}/authentication/config/{id}",
        path_params=[REALM, CONFIG_ID],
        query_params=[],
        body_param=Param(
            "config_data",
            "Authenticator configuration data to update",
            required=True,
            param_type="object",
        ),
    ),
    # ── Execution Config ─────────────────────────────────────────────────
    EndpointDef(
        name="create_execution_config",
        description="Create a new configuration for an authentication execution.",
        method="POST",
        path="/admin/realms/{realm}/authentication/executions/{execution_id}/config",
        path_params=[REALM, EXECUTION_ID],
        query_params=[],
        body_param=Param(
            "config_data",
            "Configuration data for the execution",
            required=True,
            param_type="object",
        ),
    ),
    EndpointDef(
        name="get_execution_config",
        description="Get the configuration for an authentication execution by execution ID and config ID.",
        method="GET",
        path="/admin/realms/{realm}/authentication/executions/{execution_id}/config/{id}",
        path_params=[REALM, EXECUTION_ID, CONFIG_ID],
        query_params=[],
        body_param=None,
    ),
    # ── Auth Executions ──────────────────────────────────────────────────
    EndpointDef(
        name="delete_auth_execution",
        description="Delete an authentication execution by ID.",
        method="DELETE",
        path="/admin/realms/{realm}/authentication/executions/{execution_id}",
        path_params=[REALM, EXECUTION_ID],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="get_auth_execution",
        description="Get an authentication execution by ID.",
        method="GET",
        path="/admin/realms/{realm}/authentication/executions/{execution_id}",
        path_params=[REALM, EXECUTION_ID],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="lower_auth_execution_priority",
        description="Lower the priority of an authentication execution (move it down in the flow).",
        method="POST",
        path="/admin/realms/{realm}/authentication/executions/{execution_id}/lower-priority",
        path_params=[REALM, EXECUTION_ID],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="raise_auth_execution_priority",
        description="Raise the priority of an authentication execution (move it up in the flow).",
        method="POST",
        path="/admin/realms/{realm}/authentication/executions/{execution_id}/raise-priority",
        path_params=[REALM, EXECUTION_ID],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="add_auth_execution",
        description="Add a new authentication execution to the realm.",
        method="POST",
        path="/admin/realms/{realm}/authentication/executions",
        path_params=[REALM],
        query_params=[],
        body_param=Param(
            "execution_data",
            "Authentication execution data to create",
            required=True,
            param_type="object",
        ),
    ),
    # ── Auth Flows ───────────────────────────────────────────────────────
    EndpointDef(
        name="copy_auth_flow",
        description="Copy an existing authentication flow under a new name.",
        method="POST",
        path="/admin/realms/{realm}/authentication/flows/{flow_alias}/copy",
        path_params=[REALM, FLOW_ALIAS],
        query_params=[],
        body_param=Param(
            "new_name_data",
            "Object containing the new name for the copied flow",
            required=True,
            param_type="object",
        ),
    ),
    EndpointDef(
        name="add_execution_to_flow",
        description="Add a new execution to an authentication flow.",
        method="POST",
        path="/admin/realms/{realm}/authentication/flows/{flow_alias}/executions/execution",
        path_params=[REALM, FLOW_ALIAS],
        query_params=[],
        body_param=Param(
            "execution_data",
            "Execution data to add to the flow",
            required=True,
            param_type="object",
        ),
    ),
    EndpointDef(
        name="add_flow_with_execution",
        description="Add a new flow with a new execution to an existing authentication flow.",
        method="POST",
        path="/admin/realms/{realm}/authentication/flows/{flow_alias}/executions/flow",
        path_params=[REALM, FLOW_ALIAS],
        query_params=[],
        body_param=Param(
            "flow_data",
            "Flow and execution data to add",
            required=True,
            param_type="object",
        ),
    ),
    EndpointDef(
        name="get_flow_executions",
        description="Get all executions for an authentication flow.",
        method="GET",
        path="/admin/realms/{realm}/authentication/flows/{flow_alias}/executions",
        path_params=[REALM, FLOW_ALIAS],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="update_flow_executions",
        description="Update the executions of an authentication flow.",
        method="PUT",
        path="/admin/realms/{realm}/authentication/flows/{flow_alias}/executions",
        path_params=[REALM, FLOW_ALIAS],
        query_params=[],
        body_param=Param(
            "execution_data",
            "Updated execution data for the flow",
            required=True,
            param_type="object",
        ),
    ),
    EndpointDef(
        name="list_auth_flows",
        description="List all authentication flows in the realm.",
        method="GET",
        path="/admin/realms/{realm}/authentication/flows",
        path_params=[REALM],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="delete_auth_flow",
        description="Delete an authentication flow by ID.",
        method="DELETE",
        path="/admin/realms/{realm}/authentication/flows/{id}",
        path_params=[REALM, FLOW_ID],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="get_auth_flow",
        description="Get an authentication flow by ID.",
        method="GET",
        path="/admin/realms/{realm}/authentication/flows/{id}",
        path_params=[REALM, FLOW_ID],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="update_auth_flow",
        description="Update an authentication flow by ID.",
        method="PUT",
        path="/admin/realms/{realm}/authentication/flows/{id}",
        path_params=[REALM, FLOW_ID],
        query_params=[],
        body_param=Param(
            "flow_data",
            "Authentication flow data to update",
            required=True,
            param_type="object",
        ),
    ),
    EndpointDef(
        name="create_auth_flow",
        description="Create a new authentication flow in the realm.",
        method="POST",
        path="/admin/realms/{realm}/authentication/flows",
        path_params=[REALM],
        query_params=[],
        body_param=Param(
            "flow_data",
            "Authentication flow data to create",
            required=True,
            param_type="object",
        ),
    ),
    # ── Form Providers ───────────────────────────────────────────────────
    EndpointDef(
        name="list_form_action_providers",
        description="List all form action providers available in the realm.",
        method="GET",
        path="/admin/realms/{realm}/authentication/form-action-providers",
        path_params=[REALM],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="list_form_providers",
        description="List all form providers available in the realm.",
        method="GET",
        path="/admin/realms/{realm}/authentication/form-providers",
        path_params=[REALM],
        query_params=[],
        body_param=None,
    ),
    # ── Per-Client Config Description ────────────────────────────────────
    EndpointDef(
        name="get_per_client_config_description",
        description="Get the per-client configuration description for authentication.",
        method="GET",
        path="/admin/realms/{realm}/authentication/per-client-config-description",
        path_params=[REALM],
        query_params=[],
        body_param=None,
    ),
    # ── Required Actions ─────────────────────────────────────────────────
    EndpointDef(
        name="register_required_action",
        description="Register a new required action in the realm.",
        method="POST",
        path="/admin/realms/{realm}/authentication/register-required-action",
        path_params=[REALM],
        query_params=[],
        body_param=Param(
            "action_data",
            "Required action registration data",
            required=True,
            param_type="object",
        ),
    ),
    EndpointDef(
        name="delete_required_action_config",
        description="Delete the configuration for a required action by alias.",
        method="DELETE",
        path="/admin/realms/{realm}/authentication/required-actions/{alias}/config",
        path_params=[REALM, ALIAS],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="get_required_action_config_description",
        description="Get the configuration description for a required action by alias.",
        method="GET",
        path="/admin/realms/{realm}/authentication/required-actions/{alias}/config-description",
        path_params=[REALM, ALIAS],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="get_required_action_config",
        description="Get the configuration for a required action by alias.",
        method="GET",
        path="/admin/realms/{realm}/authentication/required-actions/{alias}/config",
        path_params=[REALM, ALIAS],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="update_required_action_config",
        description="Update the configuration for a required action by alias.",
        method="PUT",
        path="/admin/realms/{realm}/authentication/required-actions/{alias}/config",
        path_params=[REALM, ALIAS],
        query_params=[],
        body_param=Param(
            "config_data",
            "Required action configuration data to update",
            required=True,
            param_type="object",
        ),
    ),
    EndpointDef(
        name="delete_required_action",
        description="Delete a required action by alias.",
        method="DELETE",
        path="/admin/realms/{realm}/authentication/required-actions/{alias}",
        path_params=[REALM, ALIAS],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="get_required_action",
        description="Get a required action by alias.",
        method="GET",
        path="/admin/realms/{realm}/authentication/required-actions/{alias}",
        path_params=[REALM, ALIAS],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="update_required_action",
        description="Update a required action by alias.",
        method="PUT",
        path="/admin/realms/{realm}/authentication/required-actions/{alias}",
        path_params=[REALM, ALIAS],
        query_params=[],
        body_param=Param(
            "action_data",
            "Required action data to update",
            required=True,
            param_type="object",
        ),
    ),
    EndpointDef(
        name="lower_required_action_priority",
        description="Lower the priority of a required action (move it down in the list).",
        method="POST",
        path="/admin/realms/{realm}/authentication/required-actions/{alias}/lower-priority",
        path_params=[REALM, ALIAS],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="raise_required_action_priority",
        description="Raise the priority of a required action (move it up in the list).",
        method="POST",
        path="/admin/realms/{realm}/authentication/required-actions/{alias}/raise-priority",
        path_params=[REALM, ALIAS],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="list_required_actions",
        description="List all required actions in the realm.",
        method="GET",
        path="/admin/realms/{realm}/authentication/required-actions",
        path_params=[REALM],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="list_unregistered_required_actions",
        description="List all unregistered required actions in the realm.",
        method="GET",
        path="/admin/realms/{realm}/authentication/unregistered-required-actions",
        path_params=[REALM],
        query_params=[],
        body_param=None,
    ),
]
