from . import EndpointDef, Param, REALM

CLIENT_SCOPE_ID = Param("client_scope_id", "Client scope ID")
GROUP_ID = Param("group_id", "Group ID")
LOCALE = Param("locale", "Locale code")
KEY = Param("key", "Localization key")

ENDPOINTS: list[EndpointDef] = [
    # ── Realms CRUD ─────────────────────────────────────────────────
    EndpointDef(
        name="list_realms",
        description="List all realms accessible to the caller.",
        method="GET",
        path="/admin/realms",
        path_params=[],
        query_params=[
            Param(
                "briefRepresentation",
                "If true, return brief representation",
                required=False,
                param_type="boolean",
            ),
        ],
        body_param=None,
    ),
    EndpointDef(
        name="create_realm",
        description="Create a new realm.",
        method="POST",
        path="/admin/realms",
        path_params=[],
        query_params=[],
        body_param=Param("realm_data", "Realm representation", param_type="object"),
    ),
    EndpointDef(
        name="get_realm",
        description="Get a realm by name.",
        method="GET",
        path="/admin/realms/{realm}",
        path_params=[REALM],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="update_realm",
        description="Update a realm.",
        method="PUT",
        path="/admin/realms/{realm}",
        path_params=[REALM],
        query_params=[],
        body_param=Param("realm_data", "Realm representation", param_type="object"),
    ),
    EndpointDef(
        name="delete_realm",
        description="Delete a realm.",
        method="DELETE",
        path="/admin/realms/{realm}",
        path_params=[REALM],
        query_params=[],
        body_param=None,
    ),
    # ── Admin Events ────────────────────────────────────────────────
    EndpointDef(
        name="list_admin_events",
        description="List admin events for the realm.",
        method="GET",
        path="/admin/realms/{realm}/admin-events",
        path_params=[REALM],
        query_params=[
            Param("operationTypes", "Operation types to filter by", required=False),
            Param("authRealm", "Auth realm to filter by", required=False),
            Param("authClient", "Auth client to filter by", required=False),
            Param("authUser", "Auth user to filter by", required=False),
            Param("authIpAddress", "Auth IP address to filter by", required=False),
            Param("resourcePath", "Resource path to filter by", required=False),
            Param("dateFrom", "Date from (inclusive)", required=False),
            Param("dateTo", "Date to (inclusive)", required=False),
            Param("first", "Pagination offset", required=False, param_type="integer"),
            Param("max", "Maximum results size", required=False, param_type="integer"),
        ],
        body_param=None,
    ),
    EndpointDef(
        name="clear_admin_events",
        description="Clear all admin events for the realm.",
        method="DELETE",
        path="/admin/realms/{realm}/admin-events",
        path_params=[REALM],
        query_params=[],
        body_param=None,
    ),
    # ── Realm Events ────────────────────────────────────────────────
    EndpointDef(
        name="list_realm_events",
        description="List events for the realm.",
        method="GET",
        path="/admin/realms/{realm}/events",
        path_params=[REALM],
        query_params=[
            Param("type", "Event type to filter by", required=False),
            Param("client", "Client to filter by", required=False),
            Param("user", "User to filter by", required=False),
            Param("dateFrom", "Date from (inclusive)", required=False),
            Param("dateTo", "Date to (inclusive)", required=False),
            Param("ipAddress", "IP address to filter by", required=False),
            Param("first", "Pagination offset", required=False, param_type="integer"),
            Param("max", "Maximum results size", required=False, param_type="integer"),
        ],
        body_param=None,
    ),
    EndpointDef(
        name="clear_realm_events",
        description="Clear all events for the realm.",
        method="DELETE",
        path="/admin/realms/{realm}/events",
        path_params=[REALM],
        query_params=[],
        body_param=None,
    ),
    # ── Events Config ───────────────────────────────────────────────
    EndpointDef(
        name="get_realm_events_config",
        description="Get the events configuration for the realm.",
        method="GET",
        path="/admin/realms/{realm}/events/config",
        path_params=[REALM],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="update_realm_events_config",
        description="Update the events configuration for the realm.",
        method="PUT",
        path="/admin/realms/{realm}/events/config",
        path_params=[REALM],
        query_params=[],
        body_param=Param(
            "events_config", "Events configuration representation", param_type="object"
        ),
    ),
    # ── Sessions & Export/Import ────────────────────────────────────
    EndpointDef(
        name="logout_all_realm_sessions",
        description="Log out all sessions for the realm.",
        method="POST",
        path="/admin/realms/{realm}/logout-all",
        path_params=[REALM],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="partial_export_realm",
        description="Partial export of the realm configuration.",
        method="POST",
        path="/admin/realms/{realm}/partial-export",
        path_params=[REALM],
        query_params=[
            Param(
                "exportClients",
                "If true, export clients",
                required=False,
                param_type="boolean",
            ),
            Param(
                "exportGroupsAndRoles",
                "If true, export groups and roles",
                required=False,
                param_type="boolean",
            ),
        ],
        body_param=None,
    ),
    EndpointDef(
        name="partial_import_realm",
        description="Partial import into the realm.",
        method="POST",
        path="/admin/realms/{realm}/partial-import",
        path_params=[REALM],
        query_params=[],
        body_param=Param(
            "import_data", "Partial import representation", param_type="object"
        ),
    ),
    # ── Users Management Permissions ────────────────────────────────
    EndpointDef(
        name="get_users_management_permissions",
        description="Get users management permissions for the realm.",
        method="GET",
        path="/admin/realms/{realm}/users-management-permissions",
        path_params=[REALM],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="update_users_management_permissions",
        description="Update users management permissions for the realm.",
        method="PUT",
        path="/admin/realms/{realm}/users-management-permissions",
        path_params=[REALM],
        query_params=[],
        body_param=Param(
            "permissions_data",
            "Management permissions representation",
            param_type="object",
        ),
    ),
    # ── Client Session Stats ────────────────────────────────────────
    EndpointDef(
        name="get_client_session_stats",
        description="Get client session stats for the realm.",
        method="GET",
        path="/admin/realms/{realm}/client-session-stats",
        path_params=[REALM],
        query_params=[],
        body_param=None,
    ),
    # ── Credential Registrators ─────────────────────────────────────
    EndpointDef(
        name="list_credential_registrators",
        description="List credential registrators for the realm.",
        method="GET",
        path="/admin/realms/{realm}/credential-registrators",
        path_params=[REALM],
        query_params=[],
        body_param=None,
    ),
    # ── Default Default Client Scopes ───────────────────────────────
    EndpointDef(
        name="list_default_default_client_scopes",
        description="List default default client scopes for the realm.",
        method="GET",
        path="/admin/realms/{realm}/default-default-client-scopes",
        path_params=[REALM],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="add_default_default_client_scope",
        description="Add a client scope to the default default client scopes of the realm.",
        method="PUT",
        path="/admin/realms/{realm}/default-default-client-scopes/{client_scope_id}",
        path_params=[REALM, CLIENT_SCOPE_ID],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="remove_default_default_client_scope",
        description="Remove a client scope from the default default client scopes of the realm.",
        method="DELETE",
        path="/admin/realms/{realm}/default-default-client-scopes/{client_scope_id}",
        path_params=[REALM, CLIENT_SCOPE_ID],
        query_params=[],
        body_param=None,
    ),
    # ── Default Groups ──────────────────────────────────────────────
    EndpointDef(
        name="list_default_groups",
        description="List default groups for the realm.",
        method="GET",
        path="/admin/realms/{realm}/default-groups",
        path_params=[REALM],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="add_default_group",
        description="Add a group to the default groups of the realm.",
        method="PUT",
        path="/admin/realms/{realm}/default-groups/{group_id}",
        path_params=[REALM, GROUP_ID],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="remove_default_group",
        description="Remove a group from the default groups of the realm.",
        method="DELETE",
        path="/admin/realms/{realm}/default-groups/{group_id}",
        path_params=[REALM, GROUP_ID],
        query_params=[],
        body_param=None,
    ),
    # ── Default Optional Client Scopes ──────────────────────────────
    EndpointDef(
        name="list_default_optional_client_scopes",
        description="List default optional client scopes for the realm.",
        method="GET",
        path="/admin/realms/{realm}/default-optional-client-scopes",
        path_params=[REALM],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="add_default_optional_client_scope",
        description="Add a client scope to the default optional client scopes of the realm.",
        method="PUT",
        path="/admin/realms/{realm}/default-optional-client-scopes/{client_scope_id}",
        path_params=[REALM, CLIENT_SCOPE_ID],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="remove_default_optional_client_scope",
        description="Remove a client scope from the default optional client scopes of the realm.",
        method="DELETE",
        path="/admin/realms/{realm}/default-optional-client-scopes/{client_scope_id}",
        path_params=[REALM, CLIENT_SCOPE_ID],
        query_params=[],
        body_param=None,
    ),
    # ── Group by Path ───────────────────────────────────────────────
    EndpointDef(
        name="get_group_by_path",
        description="Get a group by its path.",
        method="GET",
        path="/admin/realms/{realm}/group-by-path/{path}",
        path_params=[REALM, Param("path", "Group path")],
        query_params=[],
        body_param=None,
    ),
    # ── Push Revocation ─────────────────────────────────────────────
    EndpointDef(
        name="push_realm_revocation_policy",
        description="Push the realm's revocation policy to any client that has an admin URL.",
        method="POST",
        path="/admin/realms/{realm}/push-revocation",
        path_params=[REALM],
        query_params=[],
        body_param=None,
    ),
    # ── Test SMTP Connection ────────────────────────────────────────
    EndpointDef(
        name="test_smtp_connection",
        description="Test SMTP connection with the given configuration.",
        method="POST",
        path="/admin/realms/{realm}/testSMTPConnection",
        path_params=[REALM],
        query_params=[],
        body_param=Param(
            "smtp_config", "SMTP connection configuration", param_type="object"
        ),
    ),
    # ── Localization ────────────────────────────────────────────────
    EndpointDef(
        name="list_realm_localization_locales",
        description="List all locales that have localization texts configured for the realm.",
        method="GET",
        path="/admin/realms/{realm}/localization",
        path_params=[REALM],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="get_realm_localization_texts",
        description="Get all localization texts for a locale in the realm.",
        method="GET",
        path="/admin/realms/{realm}/localization/{locale}",
        path_params=[REALM, LOCALE],
        query_params=[
            Param(
                "useRealmDefaultLocaleFallback",
                "If true, fall back to the realm default locale",
                required=False,
                param_type="boolean",
            ),
        ],
        body_param=None,
    ),
    EndpointDef(
        name="update_realm_localization_texts",
        description="Update localization texts for a locale in the realm.",
        method="PUT",
        path="/admin/realms/{realm}/localization/{locale}",
        path_params=[REALM, LOCALE],
        query_params=[],
        body_param=Param("texts_data", "Localization texts map", param_type="object"),
    ),
    EndpointDef(
        name="delete_realm_localization_locale",
        description="Delete all localization texts for a locale in the realm.",
        method="DELETE",
        path="/admin/realms/{realm}/localization/{locale}",
        path_params=[REALM, LOCALE],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="get_realm_localization_text",
        description="Get a specific localization text by locale and key.",
        method="GET",
        path="/admin/realms/{realm}/localization/{locale}/{key}",
        path_params=[REALM, LOCALE, KEY],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="set_realm_localization_text",
        description="Set a specific localization text by locale and key.",
        method="PUT",
        path="/admin/realms/{realm}/localization/{locale}/{key}",
        path_params=[REALM, LOCALE, KEY],
        query_params=[],
        body_param=Param("text_value", "Localization text value", param_type="object"),
    ),
    EndpointDef(
        name="delete_realm_localization_text",
        description="Delete a specific localization text by locale and key.",
        method="DELETE",
        path="/admin/realms/{realm}/localization/{locale}/{key}",
        path_params=[REALM, LOCALE, KEY],
        query_params=[],
        body_param=None,
    ),
]
