from . import EndpointDef, Param, REALM

ROLE_NAME = Param("role_name", "Role name")
CLIENT_UUID = Param("client_uuid", "Client UUID")
TARGET_CLIENT_UUID = Param(
    "target_client_uuid", "Target client UUID for composite roles"
)

ENDPOINTS: list[EndpointDef] = [
    # ── Realm Roles CRUD ────────────────────────────────────────────────
    EndpointDef(
        name="list_realm_roles",
        description="List all roles for the realm.",
        method="GET",
        path="/admin/realms/{realm}/roles",
        path_params=[REALM],
        query_params=[
            Param("search", "Search string for role name", required=False),
            Param("first", "Pagination offset", required=False, param_type="integer"),
            Param("max", "Maximum results size", required=False, param_type="integer"),
            Param(
                "briefRepresentation",
                "If true, return brief representation",
                required=False,
                param_type="boolean",
            ),
        ],
        body_param=None,
    ),
    EndpointDef(
        name="create_realm_role",
        description="Create a new realm role.",
        method="POST",
        path="/admin/realms/{realm}/roles",
        path_params=[REALM],
        query_params=[],
        body_param=Param("role_data", "Role representation", param_type="object"),
    ),
    EndpointDef(
        name="get_realm_role",
        description="Get a realm role by name.",
        method="GET",
        path="/admin/realms/{realm}/roles/{role_name}",
        path_params=[REALM, ROLE_NAME],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="update_realm_role",
        description="Update a realm role.",
        method="PUT",
        path="/admin/realms/{realm}/roles/{role_name}",
        path_params=[REALM, ROLE_NAME],
        query_params=[],
        body_param=Param("role_data", "Role representation", param_type="object"),
    ),
    EndpointDef(
        name="delete_realm_role",
        description="Delete a realm role.",
        method="DELETE",
        path="/admin/realms/{realm}/roles/{role_name}",
        path_params=[REALM, ROLE_NAME],
        query_params=[],
        body_param=None,
    ),
    # ── Realm Role Composites ───────────────────────────────────────────
    EndpointDef(
        name="get_realm_role_composites",
        description="Get composites of a realm role.",
        method="GET",
        path="/admin/realms/{realm}/roles/{role_name}/composites",
        path_params=[REALM, ROLE_NAME],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="add_realm_role_composites",
        description="Add composites to a realm role.",
        method="POST",
        path="/admin/realms/{realm}/roles/{role_name}/composites",
        path_params=[REALM, ROLE_NAME],
        query_params=[],
        body_param=Param(
            "roles",
            "List of role representations to add as composites",
            param_type="object",
        ),
    ),
    EndpointDef(
        name="remove_realm_role_composites",
        description="Remove composites from a realm role.",
        method="DELETE",
        path="/admin/realms/{realm}/roles/{role_name}/composites",
        path_params=[REALM, ROLE_NAME],
        query_params=[],
        body_param=Param(
            "roles",
            "List of role representations to remove from composites",
            param_type="object",
        ),
    ),
    EndpointDef(
        name="get_realm_role_realm_composites",
        description="Get realm-level composites of a realm role.",
        method="GET",
        path="/admin/realms/{realm}/roles/{role_name}/composites/realm",
        path_params=[REALM, ROLE_NAME],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="get_realm_role_client_composites",
        description="Get client-level composites of a realm role for a specific client.",
        method="GET",
        path="/admin/realms/{realm}/roles/{role_name}/composites/clients/{client_uuid}",
        path_params=[REALM, ROLE_NAME, CLIENT_UUID],
        query_params=[],
        body_param=None,
    ),
    # ── Realm Role Groups & Users ───────────────────────────────────────
    EndpointDef(
        name="list_realm_role_groups",
        description="List groups that have the specified realm role.",
        method="GET",
        path="/admin/realms/{realm}/roles/{role_name}/groups",
        path_params=[REALM, ROLE_NAME],
        query_params=[
            Param("first", "Pagination offset", required=False, param_type="integer"),
            Param("max", "Maximum results size", required=False, param_type="integer"),
            Param(
                "briefRepresentation",
                "If true, return brief representation",
                required=False,
                param_type="boolean",
            ),
        ],
        body_param=None,
    ),
    EndpointDef(
        name="list_realm_role_users",
        description="List users that have the specified realm role.",
        method="GET",
        path="/admin/realms/{realm}/roles/{role_name}/users",
        path_params=[REALM, ROLE_NAME],
        query_params=[
            Param("first", "Pagination offset", required=False, param_type="integer"),
            Param("max", "Maximum results size", required=False, param_type="integer"),
        ],
        body_param=None,
    ),
    # ── Realm Role Management Permissions ───────────────────────────────
    EndpointDef(
        name="get_realm_role_permissions",
        description="Get management permissions for a realm role.",
        method="GET",
        path="/admin/realms/{realm}/roles/{role_name}/management/permissions",
        path_params=[REALM, ROLE_NAME],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="update_realm_role_permissions",
        description="Update management permissions for a realm role.",
        method="PUT",
        path="/admin/realms/{realm}/roles/{role_name}/management/permissions",
        path_params=[REALM, ROLE_NAME],
        query_params=[],
        body_param=Param(
            "permissions_data",
            "Management permissions representation",
            param_type="object",
        ),
    ),
    # ── Client Roles CRUD ───────────────────────────────────────────────
    EndpointDef(
        name="list_client_roles",
        description="List all roles for a client.",
        method="GET",
        path="/admin/realms/{realm}/clients/{client_uuid}/roles",
        path_params=[REALM, CLIENT_UUID],
        query_params=[
            Param("search", "Search string for role name", required=False),
            Param("first", "Pagination offset", required=False, param_type="integer"),
            Param("max", "Maximum results size", required=False, param_type="integer"),
            Param(
                "briefRepresentation",
                "If true, return brief representation",
                required=False,
                param_type="boolean",
            ),
        ],
        body_param=None,
    ),
    EndpointDef(
        name="create_client_role",
        description="Create a new client role.",
        method="POST",
        path="/admin/realms/{realm}/clients/{client_uuid}/roles",
        path_params=[REALM, CLIENT_UUID],
        query_params=[],
        body_param=Param("role_data", "Role representation", param_type="object"),
    ),
    EndpointDef(
        name="get_client_role",
        description="Get a client role by name.",
        method="GET",
        path="/admin/realms/{realm}/clients/{client_uuid}/roles/{role_name}",
        path_params=[REALM, CLIENT_UUID, ROLE_NAME],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="update_client_role",
        description="Update a client role.",
        method="PUT",
        path="/admin/realms/{realm}/clients/{client_uuid}/roles/{role_name}",
        path_params=[REALM, CLIENT_UUID, ROLE_NAME],
        query_params=[],
        body_param=Param("role_data", "Role representation", param_type="object"),
    ),
    EndpointDef(
        name="delete_client_role",
        description="Delete a client role.",
        method="DELETE",
        path="/admin/realms/{realm}/clients/{client_uuid}/roles/{role_name}",
        path_params=[REALM, CLIENT_UUID, ROLE_NAME],
        query_params=[],
        body_param=None,
    ),
    # ── Client Role Composites ──────────────────────────────────────────
    EndpointDef(
        name="get_client_role_composites",
        description="Get composites of a client role.",
        method="GET",
        path="/admin/realms/{realm}/clients/{client_uuid}/roles/{role_name}/composites",
        path_params=[REALM, CLIENT_UUID, ROLE_NAME],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="add_client_role_composites",
        description="Add composites to a client role.",
        method="POST",
        path="/admin/realms/{realm}/clients/{client_uuid}/roles/{role_name}/composites",
        path_params=[REALM, CLIENT_UUID, ROLE_NAME],
        query_params=[],
        body_param=Param(
            "roles",
            "List of role representations to add as composites",
            param_type="object",
        ),
    ),
    EndpointDef(
        name="remove_client_role_composites",
        description="Remove composites from a client role.",
        method="DELETE",
        path="/admin/realms/{realm}/clients/{client_uuid}/roles/{role_name}/composites",
        path_params=[REALM, CLIENT_UUID, ROLE_NAME],
        query_params=[],
        body_param=Param(
            "roles",
            "List of role representations to remove from composites",
            param_type="object",
        ),
    ),
    EndpointDef(
        name="get_client_role_realm_composites",
        description="Get realm-level composites of a client role.",
        method="GET",
        path="/admin/realms/{realm}/clients/{client_uuid}/roles/{role_name}/composites/realm",
        path_params=[REALM, CLIENT_UUID, ROLE_NAME],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="get_client_role_client_composites",
        description="Get client-level composites of a client role for a specific target client.",
        method="GET",
        path="/admin/realms/{realm}/clients/{client_uuid}/roles/{role_name}/composites/clients/{target_client_uuid}",
        path_params=[REALM, CLIENT_UUID, ROLE_NAME, TARGET_CLIENT_UUID],
        query_params=[],
        body_param=None,
    ),
    # ── Client Role Groups & Users ──────────────────────────────────────
    EndpointDef(
        name="list_client_role_groups",
        description="List groups that have the specified client role.",
        method="GET",
        path="/admin/realms/{realm}/clients/{client_uuid}/roles/{role_name}/groups",
        path_params=[REALM, CLIENT_UUID, ROLE_NAME],
        query_params=[
            Param("first", "Pagination offset", required=False, param_type="integer"),
            Param("max", "Maximum results size", required=False, param_type="integer"),
            Param(
                "briefRepresentation",
                "If true, return brief representation",
                required=False,
                param_type="boolean",
            ),
        ],
        body_param=None,
    ),
    EndpointDef(
        name="list_client_role_users",
        description="List users that have the specified client role.",
        method="GET",
        path="/admin/realms/{realm}/clients/{client_uuid}/roles/{role_name}/users",
        path_params=[REALM, CLIENT_UUID, ROLE_NAME],
        query_params=[
            Param("first", "Pagination offset", required=False, param_type="integer"),
            Param("max", "Maximum results size", required=False, param_type="integer"),
        ],
        body_param=None,
    ),
    # ── Client Role Management Permissions ──────────────────────────────
    EndpointDef(
        name="get_client_role_permissions",
        description="Get management permissions for a client role.",
        method="GET",
        path="/admin/realms/{realm}/clients/{client_uuid}/roles/{role_name}/management/permissions",
        path_params=[REALM, CLIENT_UUID, ROLE_NAME],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="update_client_role_permissions",
        description="Update management permissions for a client role.",
        method="PUT",
        path="/admin/realms/{realm}/clients/{client_uuid}/roles/{role_name}/management/permissions",
        path_params=[REALM, CLIENT_UUID, ROLE_NAME],
        query_params=[],
        body_param=Param(
            "permissions_data",
            "Management permissions representation",
            param_type="object",
        ),
    ),
]
