from . import EndpointDef, Param, REALM

CLIENT_SCOPE_ID = Param("client_scope_id", "Client scope ID")
CLIENT_UUID = Param("client_uuid", "Client UUID")
USER_ID = Param("user_id", "User ID")
GROUP_ID = Param("group_id", "Group ID")

ENDPOINTS: list[EndpointDef] = [
    # ── Client Scope → Scope Mappings ──────────────────────────────────
    EndpointDef(
        name="get_client_scope_scope_mappings",
        description="Get all scope mappings for a client scope.",
        method="GET",
        path="/admin/realms/{realm}/client-scopes/{client_scope_id}/scope-mappings",
        path_params=[REALM, CLIENT_SCOPE_ID],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="get_client_scope_realm_scope_mappings",
        description="Get realm-level roles associated with a client scope's scope.",
        method="GET",
        path="/admin/realms/{realm}/client-scopes/{client_scope_id}/scope-mappings/realm",
        path_params=[REALM, CLIENT_SCOPE_ID],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="add_client_scope_realm_scope_mappings",
        description="Add realm-level roles to a client scope's scope.",
        method="POST",
        path="/admin/realms/{realm}/client-scopes/{client_scope_id}/scope-mappings/realm",
        path_params=[REALM, CLIENT_SCOPE_ID],
        query_params=[],
        body_param=Param("roles", "List of role representations", param_type="object"),
    ),
    EndpointDef(
        name="remove_client_scope_realm_scope_mappings",
        description="Remove realm-level roles from a client scope's scope.",
        method="DELETE",
        path="/admin/realms/{realm}/client-scopes/{client_scope_id}/scope-mappings/realm",
        path_params=[REALM, CLIENT_SCOPE_ID],
        query_params=[],
        body_param=Param("roles", "List of role representations", param_type="object"),
    ),
    EndpointDef(
        name="get_available_client_scope_realm_scope_mappings",
        description="Get realm-level roles available to add to a client scope's scope.",
        method="GET",
        path="/admin/realms/{realm}/client-scopes/{client_scope_id}/scope-mappings/realm/available",
        path_params=[REALM, CLIENT_SCOPE_ID],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="get_effective_client_scope_realm_scope_mappings",
        description="Get effective (composite) realm-level roles for a client scope's scope.",
        method="GET",
        path="/admin/realms/{realm}/client-scopes/{client_scope_id}/scope-mappings/realm/composite",
        path_params=[REALM, CLIENT_SCOPE_ID],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="get_client_scope_client_scope_mappings",
        description="Get client-level roles associated with a client scope's scope.",
        method="GET",
        path="/admin/realms/{realm}/client-scopes/{client_scope_id}/scope-mappings/clients/{client_uuid}",
        path_params=[REALM, CLIENT_SCOPE_ID, CLIENT_UUID],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="add_client_scope_client_scope_mappings",
        description="Add client-level roles to a client scope's scope.",
        method="POST",
        path="/admin/realms/{realm}/client-scopes/{client_scope_id}/scope-mappings/clients/{client_uuid}",
        path_params=[REALM, CLIENT_SCOPE_ID, CLIENT_UUID],
        query_params=[],
        body_param=Param("roles", "List of role representations", param_type="object"),
    ),
    EndpointDef(
        name="remove_client_scope_client_scope_mappings",
        description="Remove client-level roles from a client scope's scope.",
        method="DELETE",
        path="/admin/realms/{realm}/client-scopes/{client_scope_id}/scope-mappings/clients/{client_uuid}",
        path_params=[REALM, CLIENT_SCOPE_ID, CLIENT_UUID],
        query_params=[],
        body_param=Param("roles", "List of role representations", param_type="object"),
    ),
    EndpointDef(
        name="get_available_client_scope_client_scope_mappings",
        description="Get available client-level roles that can be added to a client scope's scope.",
        method="GET",
        path="/admin/realms/{realm}/client-scopes/{client_scope_id}/scope-mappings/clients/{client_uuid}/available",
        path_params=[REALM, CLIENT_SCOPE_ID, CLIENT_UUID],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="get_effective_client_scope_client_scope_mappings",
        description="Get effective (composite) client-level roles for a client scope's scope.",
        method="GET",
        path="/admin/realms/{realm}/client-scopes/{client_scope_id}/scope-mappings/clients/{client_uuid}/composite",
        path_params=[REALM, CLIENT_SCOPE_ID, CLIENT_UUID],
        query_params=[],
        body_param=None,
    ),
    # ── Client → Scope Mappings ────────────────────────────────────────
    EndpointDef(
        name="get_client_scope_mappings_all",
        description="Get all scope mappings for a client.",
        method="GET",
        path="/admin/realms/{realm}/clients/{client_uuid}/scope-mappings",
        path_params=[REALM, CLIENT_UUID],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="get_client_realm_scope_mappings",
        description="Get realm-level roles associated with a client's scope.",
        method="GET",
        path="/admin/realms/{realm}/clients/{client_uuid}/scope-mappings/realm",
        path_params=[REALM, CLIENT_UUID],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="add_client_realm_scope_mappings",
        description="Add realm-level roles to a client's scope.",
        method="POST",
        path="/admin/realms/{realm}/clients/{client_uuid}/scope-mappings/realm",
        path_params=[REALM, CLIENT_UUID],
        query_params=[],
        body_param=Param("roles", "List of role representations", param_type="object"),
    ),
    EndpointDef(
        name="remove_client_realm_scope_mappings",
        description="Remove realm-level roles from a client's scope.",
        method="DELETE",
        path="/admin/realms/{realm}/clients/{client_uuid}/scope-mappings/realm",
        path_params=[REALM, CLIENT_UUID],
        query_params=[],
        body_param=Param("roles", "List of role representations", param_type="object"),
    ),
    EndpointDef(
        name="get_available_client_realm_scope_mappings",
        description="Get realm-level roles available to add to a client's scope.",
        method="GET",
        path="/admin/realms/{realm}/clients/{client_uuid}/scope-mappings/realm/available",
        path_params=[REALM, CLIENT_UUID],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="get_effective_client_realm_scope_mappings",
        description="Get effective (composite) realm-level roles for a client's scope.",
        method="GET",
        path="/admin/realms/{realm}/clients/{client_uuid}/scope-mappings/realm/composite",
        path_params=[REALM, CLIENT_UUID],
        query_params=[],
        body_param=None,
    ),
    # ── User Role Mappings ─────────────────────────────────────────────
    EndpointDef(
        name="get_user_role_mappings",
        description="Get all role mappings for a user.",
        method="GET",
        path="/admin/realms/{realm}/users/{user_id}/role-mappings",
        path_params=[REALM, USER_ID],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="get_user_realm_role_mappings",
        description="Get realm-level role mappings for a user.",
        method="GET",
        path="/admin/realms/{realm}/users/{user_id}/role-mappings/realm",
        path_params=[REALM, USER_ID],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="add_user_realm_role_mappings",
        description="Add realm-level role mappings to a user.",
        method="POST",
        path="/admin/realms/{realm}/users/{user_id}/role-mappings/realm",
        path_params=[REALM, USER_ID],
        query_params=[],
        body_param=Param("roles", "List of role representations", param_type="object"),
    ),
    EndpointDef(
        name="remove_user_realm_role_mappings",
        description="Remove realm-level role mappings from a user.",
        method="DELETE",
        path="/admin/realms/{realm}/users/{user_id}/role-mappings/realm",
        path_params=[REALM, USER_ID],
        query_params=[],
        body_param=Param("roles", "List of role representations", param_type="object"),
    ),
    EndpointDef(
        name="get_available_user_realm_roles",
        description="Get realm-level roles available to map to a user.",
        method="GET",
        path="/admin/realms/{realm}/users/{user_id}/role-mappings/realm/available",
        path_params=[REALM, USER_ID],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="get_effective_user_realm_role_mappings",
        description="Get effective (composite) realm-level role mappings for a user.",
        method="GET",
        path="/admin/realms/{realm}/users/{user_id}/role-mappings/realm/composite",
        path_params=[REALM, USER_ID],
        query_params=[],
        body_param=None,
    ),
    # ── Group Role Mappings ────────────────────────────────────────────
    EndpointDef(
        name="get_group_role_mappings",
        description="Get all role mappings for a group.",
        method="GET",
        path="/admin/realms/{realm}/groups/{group_id}/role-mappings",
        path_params=[REALM, GROUP_ID],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="get_group_realm_role_mappings",
        description="Get realm-level role mappings for a group.",
        method="GET",
        path="/admin/realms/{realm}/groups/{group_id}/role-mappings/realm",
        path_params=[REALM, GROUP_ID],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="add_group_realm_role_mappings",
        description="Add realm-level role mappings to a group.",
        method="POST",
        path="/admin/realms/{realm}/groups/{group_id}/role-mappings/realm",
        path_params=[REALM, GROUP_ID],
        query_params=[],
        body_param=Param("roles", "List of role representations", param_type="object"),
    ),
    EndpointDef(
        name="remove_group_realm_role_mappings",
        description="Remove realm-level role mappings from a group.",
        method="DELETE",
        path="/admin/realms/{realm}/groups/{group_id}/role-mappings/realm",
        path_params=[REALM, GROUP_ID],
        query_params=[],
        body_param=Param("roles", "List of role representations", param_type="object"),
    ),
    EndpointDef(
        name="get_available_group_realm_roles",
        description="Get realm-level roles available to map to a group.",
        method="GET",
        path="/admin/realms/{realm}/groups/{group_id}/role-mappings/realm/available",
        path_params=[REALM, GROUP_ID],
        query_params=[],
        body_param=None,
    ),
    EndpointDef(
        name="get_effective_group_realm_role_mappings",
        description="Get effective (composite) realm-level role mappings for a group.",
        method="GET",
        path="/admin/realms/{realm}/groups/{group_id}/role-mappings/realm/composite",
        path_params=[REALM, GROUP_ID],
        query_params=[],
        body_param=None,
    ),
]
